services:
  resolver:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: dns_resolver
    ports:
      - "8053:8053"
      - "9091:9091"
    networks:
      - dnsnet

  prometheus:
    image: prom/prometheus:latest
    container_name: dns_prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - ./alert.rules.yml:/etc/prometheus/alert.rules.yml
    networks:
      - dnsnet

  grafana:
    image: grafana/grafana
    container_name: dns_grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning
      - ./grafana/dashboards:/var/lib/grafana/dashboards
    networks:
      - dnsnet

networks:
  dnsnet:
    driver: bridge

volumes:
  grafana_data:
