{
 "title": "scr",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "95th-Pct Upstream RTT",
   "type": "timeseries",
   "gridPos": { "h": 15, "w": 5, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(\r\n  0.95,\r\n  sum(rate(dns_upstream_rtt_seconds_bucket[5m]))\r\n    by (le, upstream)\r\n)",
     "legendFormat": "{{upstream}}"
    }
   ]
  },
  {
   "title": "Cache Hit %",
   "type": "gauge",
   "gridPos": { "h": 15, "w": 7, "x": 5, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 * sum(rate(dns_cache_hits_total[1m]))\r\n  / sum(rate(dns_queries_total[1m]))\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "DNS Queries /sec",
   "type": "timeseries",
   "gridPos": { "h": 23, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "rate(dns_queries_total[1m])\r\n",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Upstream Selections /sec",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 15 },
   "targets": [
    {
     "expr": "sum by (upstream)(rate(dns_upstream_selection_total[1m]))",
     "legendFormat": "{{upstream}}"
    }
   ]
  }
 ]
}